### ISSUE TITLE
Love the design but just need N64

### ISSUE THREAD

**Issue by zezretro** [timville85/4dapter#2]
Hiya

I need just the N64 part and I live way on the other side of Europe so shipping is a lot

I would happily use a Arudino and wire in the N64 port. I see the issue is with providing 3.3V and thats what the extra components on the pcb do.

If I just wanted to wire in a N64 port in the jankiest way possible, what components would I use between the "RAW" pin and the 3.3V on the N64 port?

thank you!

**Comment by timville85** [comment]
https://www.digikey.com/en/products/detail/stmicroelectronics/LD1117V33/586012

Connect Arduino "RAW" to "V In"
Connect Arduino "GND" to "GND"

Connect N64 3.3V to "V Out"
Connect N64 "GND" to "GND"
Connect N64 Data to Arduino Pin 10 (if using 4dapter code)

![Screenshot 2023-11-16 at 10 29 29 AM](https://github.com/timville85/4dapter/assets/31223405/02ad937b-538a-48cc-b687-a7f5ae674762)

**Comment by zezretro** [comment]
Thank you for this!
