### ISSUE TITLE
N64 controller analog stick Issue with fast left to right movements

### ISSUE THREAD

**Issue by staticaland** [timville85/4dapter#3]
## Description

**Problem**: When moving the analog stick quickly from left to right on the N64 controller, the direction isn't registering correctly. This is a big issue in games like Mario Kart 64, especially when drifting.

**Expected**: The game should track the stick movements accurately, responding right away to changes in direction.

**Actual**: The game isn't responding properly to quick side-to-side movements of the stick.

## Steps to Reproduce

1. Play Mario Kart 64.
2. Try to drift by moving the stick quickly from side to side.
3. Notice the response in-game.

**Comment by timville85** [comment]
Try updating to the latest firmware - There was an [issue](https://github.com/timville85/4dapter/commit/71547d03f5220ea4f39225e8aede2ae9bd2ea9e2) fixed where the X-axis was being scaled incorrectly. 

Latest firmware is here: https://github.com/timville85/4dapter/tree/main/4dapter_FW-HID

**Comment by staticaland** [comment]
This is fixed by updating the firmware. See https://github.com/timville85/4dapter/commit/71547d03f5220ea4f39225e8aede2ae9bd2ea9e2.

Below is what I did to upgrade the firmware.

# Step-by-Step Firmware Upgrade Process

## Step 1: Download Firmware Files

- First, navigate to the Daemonbite adapter firmware [GitHub repository](https://github.com/timville85/4dapter).
- Download the project as a ZIP file.
- Once downloaded, unzip the file to extract its contents.

## Step 2: Open the Firmware File

- Locate the `.ino` file [within the unzipped folder](https://github.com/timville85/4dapter/tree/main/4dapter_FW-HID).
- Open this file using the Arduino IDE. If you don't have the Arduino IDE installed, you can download it from the [official Arduino website](https://www.arduino.cc/en/software).

## Step 3: Select the Appropriate Port

- Connect your Daemonbite adapter to your computer.
- In the Arduino IDE, go to the `Tools` menu.
- Choose `Port` and select the port that corresponds to your connected Daemonbite adapter.

## Step 4: Select the Board

- Still in the `Tools` menu, navigate to `Board`.
- Select `Arduino Leonardo` from the list of available boards. This selection is crucial for compatibility with the Daemonbite firmware.

## Step 5: Upload the Firmware

- Once the correct port and board are selected, you can upload the firmware to your Daemonbite adapter.
- Click on the upload button in the Arduino IDE. This process will compile and upload the new firmware to your adapter.

## Step 6: Completion

- After the upload is complete, the IDE will display a message indicating successful firmware upload.
- Your Daemonbite adapter is now updated and ready to use with the new firmware.

**Comment by staticaland** [comment]
Thanks @timville85! You are too fast, I had already fixed it and just wanted to create an issue for anyone else searching for a solution 😅
