### ISSUE TITLE
lufa.h not found

### ISSUE THREAD

**Issue by DfknG** [timville85/4dapter#4]
When I was trying to write the switch firmware it references lufa.h but there is no file or directory specified.

4dapter-main\4dapter-main\4dapter_FW-Switch\4dapter_FW-Switch.ino:3:10: fatal error: LUFA.h: No such file or directory
 #include <LUFA.h>
          ^~~~~~~~
compilation terminated.
exit status 1

Compilation error: LUFA.h: No such file or directory

**Comment by timville85** [comment]
Make sure you install the LUFA boards - instructions at the bottom of the Switch readme:

https://github.com/timville85/4dapter/blob/main/4dapter_FW-Switch/README.md
