### ISSUE TITLE
No response on nintendo switch

### ISSUE THREAD

**Issue by Stefkeys** [timville85/4dapter#5]
I have uploaded the switch firmware to the 4dapter successfully. However, I am getting no response on the Nintendo switch.
I am trying to use the wireless 8bitdo controllers.
Are there some restrictions that I'm not aware of?

**Comment by timville85** [comment]
Just confirming that you've selected the Arduino LUFA board type and also are installing the Switch project from the 4dapter repo?

![Screenshot 2024-07-19 at 17 24 58](https://github.com/user-attachments/assets/c12242f9-04ad-4bd4-a713-cf96d00c9ed4)

**Comment by Stefkeys** [comment]
So the issue turns out to be that I need to have the 4dapter plugged into the switch dock prior to booting the switch. 

I have confirmed that it works.
