### ISSUE TITLE
Gamecube controller support

### ISSUE THREAD

**Issue by steelpuxnastik** [timville85/4dapter#6]
I see in schematic device "supports" gamecube controller, but beyond this there is no mention of it. Is there some radical problems with it and will it be implemented? Because I'm super interested in it. 
I see in some other projects about gamecube arduino used level shifter on data line.

**Comment by timville85** [comment]
These ports were exposed (and provided on the PCB with a header) mostly for future use/experimentation. The idea was to provide a data path (to pin 4 on the Arduino) along with 5v / 3.3v / GND to wire in a Gamecube socket. The data line would likely need a level shifter added but a final proper implementation would include one.

Basically, it was added with the idea of potential future support, but no plans on officially supporting it any time soon.

**Comment by steelpuxnastik** [comment]
That is why I asked you, because to add to this board additional board with level shifter, gamecube socket and so on not a big problem. I wanted to make it, but the only problem - it's support in firmware.
